name: Deploy

inputs:
  environment:
    required: true
  port:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./reverse-proxy-location-${{ inputs.environment }}}
        file: ./reverse-proxy-location-${{ inputs.environment }}/Dockerfile
        push: true
        tags: ablaszkiewicz/redirector-proxy-location-${{ inputs.environment }}:latest
  # update-VPS-container:
  #   needs: build-and-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Update image inside VPS
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST }}
  #         USERNAME: ${{ secrets.USERNAME }}
  #         PORT: ${{ secrets.PORT }}
  #         KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           docker stop $(docker ps -q --filter ancestor=ablaszkiewicz/redirector-proxy-location-${{ inputs.environment }} )
  #           docker pull ablaszkiewicz/redirector-proxy-location-${{ inputs.environment }}
  #           docker run -d -p ${{ inputs.port }}:80 ablaszkiewicz/redirector-proxy-location-${{ inputs.environment }}
