name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/reverse-proxy-location/build-and-push'
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: ablaszkiewicz/reverse-proxy-location-dev
          context: ./reverse-proxy-location-dev
          file: ./reverse-proxy-location-dev/Dockerfile
      - name: Deploy
        uses: './.github/templates/reverse-proxy-location/deploy'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          image-name: ablaszkiewicz/reverse-proxy-location-dev
          container-port: 4080
